title                    : "Amazon CardUI Clone"
name                     : "Angelo"
description              : "Amazon CardUI Clone 작성"
url                      : "https://dev-angelo.github.io/amazon-cardui-clone/"
baseurl                  :
